# Generated by Django 3.1.1 on 2020-10-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Line_UP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_shows',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
    ]
